- name: Install Google Chrome on Windows
  hosts: windows_servers
  gather_facts: no
  tasks:
    - name: Install Google Chrome using Chocolatey
      win_chocolatey:
        name: googlechrome
        state: present
