---
- name: Install Google Chrome on Windows
  hosts: windows_servers  # Replace with the name of your Windows host or the appropriate host group
  gather_facts: no
  tasks:
    - name: Check if Chrome is already installed
      win_command: 'Get-WmiObject -Class Win32_Product | Where-Object {$_.Name -like "Google Chrome*"}'
      ignore_errors: yes
      register: chrome_check

    - name: Uninstall Chrome if already installed
      win_command: 'msiexec /uninstall {{ chrome_check.stdout_lines[0] | regex_replace(".*{(.*?)}.*", "\\1") }} /qn'
      ignore_errors: yes
      when: chrome_check.rc == 0

    - name: Download Chrome Installer
      win_command: 'Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile "C:\Temp\chrome_installer.exe"'
      ignore_errors: yes

    - name: Install Chrome from Downloaded Installer
      win_command: 'C:\Temp\chrome_installer.exe /silent /install'
      ignore_errors: yes

    - name: Check Chrome installation result
      win_command: 'Get-WmiObject -Class Win32_Product | Where-Object {$_.Name -like "Google Chrome*"}'
      register: install_result

    - name: Display Chrome installation result
      debug:
        var: install_result.stdout

